# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'DanTangSwift' do
  use_frameworks!


pod 'SVProgressHUD', '~> 2.1'
pod 'Kingfisher', '~> 3.2.2'
pod 'SnapKit', '~> 3.0.2'
pod 'Alamofire', '~> 4.2.0'
pod 'SwiftyJSON', '~> 3.1.3'

end
